/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mil.sda111mil.forms;

import javax.swing.JOptionPane;

/**
 *
 * @author CF02
 */
public class FormDocente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormAlumno
     */
    public FormDocente() {
        initComponents();
        inhabilitar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registroResponsables = new javax.swing.JPanel();
        DNombre = new javax.swing.JLabel();
        txt_docente_nombre = new javax.swing.JTextField();
        DApellido = new javax.swing.JLabel();
        txt_docente_apellido = new javax.swing.JTextField();
        DDNI = new javax.swing.JLabel();
        txt_docente_dni_d = new javax.swing.JTextField();
        DTelefono = new javax.swing.JLabel();
        txt_docente_telefono_area = new javax.swing.JTextField();
        txt_docente_telefono_numero = new javax.swing.JTextField();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        telefono_0 = new javax.swing.JLabel();
        telefono_15 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        cbo_tipo_telefono = new javax.swing.JComboBox<>();
        listaResponsables = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListado = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        txt_buscar = new javax.swing.JTextField();
        lblTotalRegistros = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Docente");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registroResponsables.setBackground(new java.awt.Color(255, 230, 153));
        registroResponsables.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Docentes"));

        DNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DNombre.setText("Nombre:");
        DNombre.setMaximumSize(new java.awt.Dimension(60, 15));
        DNombre.setMinimumSize(new java.awt.Dimension(60, 15));
        DNombre.setPreferredSize(new java.awt.Dimension(60, 22));

        txt_docente_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_docente_nombre.setPreferredSize(new java.awt.Dimension(100, 25));
        txt_docente_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_docente_nombreActionPerformed(evt);
            }
        });
        txt_docente_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_docente_nombreKeyTyped(evt);
            }
        });

        DApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DApellido.setText("Apellido:");
        DApellido.setMaximumSize(new java.awt.Dimension(60, 15));
        DApellido.setMinimumSize(new java.awt.Dimension(60, 15));
        DApellido.setPreferredSize(new java.awt.Dimension(60, 22));

        txt_docente_apellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_docente_apellido.setPreferredSize(new java.awt.Dimension(100, 25));
        txt_docente_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_docente_apellidoActionPerformed(evt);
            }
        });
        txt_docente_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_docente_apellidoKeyTyped(evt);
            }
        });

        DDNI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DDNI.setText("DNI:");
        DDNI.setMaximumSize(new java.awt.Dimension(60, 15));
        DDNI.setMinimumSize(new java.awt.Dimension(60, 15));
        DDNI.setPreferredSize(new java.awt.Dimension(60, 22));

        txt_docente_dni_d.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_docente_dni_d.setPreferredSize(new java.awt.Dimension(100, 25));
        txt_docente_dni_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_docente_dni_dActionPerformed(evt);
            }
        });
        txt_docente_dni_d.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_docente_dni_dKeyTyped(evt);
            }
        });

        DTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DTelefono.setText("Teléfono:");
        DTelefono.setMaximumSize(new java.awt.Dimension(60, 15));
        DTelefono.setMinimumSize(new java.awt.Dimension(60, 15));
        DTelefono.setPreferredSize(new java.awt.Dimension(60, 22));

        txt_docente_telefono_area.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_docente_telefono_area.setMaximumSize(new java.awt.Dimension(100, 25));
        txt_docente_telefono_area.setMinimumSize(new java.awt.Dimension(100, 25));
        txt_docente_telefono_area.setPreferredSize(new java.awt.Dimension(100, 25));
        txt_docente_telefono_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_docente_telefono_areaActionPerformed(evt);
            }
        });
        txt_docente_telefono_area.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_docente_telefono_areaKeyTyped(evt);
            }
        });

        txt_docente_telefono_numero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_docente_telefono_numero.setPreferredSize(new java.awt.Dimension(100, 25));
        txt_docente_telefono_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_docente_telefono_numeroActionPerformed(evt);
            }
        });
        txt_docente_telefono_numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_docente_telefono_numeroKeyTyped(evt);
            }
        });

        btn_nuevo.setBackground(new java.awt.Color(51, 51, 51));
        btn_nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/if_Add_24x24.png"))); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.setBorder(null);
        btn_nuevo.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_guardar.setBackground(new java.awt.Color(51, 51, 51));
        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/if_Save_24x24.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(51, 51, 51));
        btn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/if_Cancel_24x24.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        telefono_0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telefono_0.setText("0");
        telefono_0.setIconTextGap(0);
        telefono_0.setPreferredSize(new java.awt.Dimension(50, 30));

        telefono_15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telefono_15.setText("15");
        telefono_15.setIconTextGap(0);
        telefono_15.setPreferredSize(new java.awt.Dimension(50, 30));

        btn_agregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        cbo_tipo_telefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbo_tipo_telefono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fijo", "Movil" }));
        cbo_tipo_telefono.setSelectedItem("Movil");
        cbo_tipo_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_tipo_telefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registroResponsablesLayout = new javax.swing.GroupLayout(registroResponsables);
        registroResponsables.setLayout(registroResponsablesLayout);
        registroResponsablesLayout.setHorizontalGroup(
            registroResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registroResponsablesLayout.createSequentialGroup()
                .addGroup(registroResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroResponsablesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registroResponsablesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(registroResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(registroResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registroResponsablesLayout.createSequentialGroup()
                                .addComponent(cbo_tipo_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefono_0, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_docente_telefono_area, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefono_15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_docente_telefono_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_agregar))
                            .addComponent(txt_docente_dni_d, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_docente_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_docente_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        registroResponsablesLayout.setVerticalGroup(
            registroResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registroResponsablesLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(registroResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_docente_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(registroResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_docente_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(registroResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_docente_dni_d, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(registroResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registroResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_agregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(registroResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_docente_telefono_area, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefono_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefono_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_docente_telefono_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_tipo_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(DTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addGroup(registroResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registroResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );

        getContentPane().add(registroResponsables, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 670));

        listaResponsables.setBackground(new java.awt.Color(255, 204, 102));
        listaResponsables.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Docentes"));

        tablaListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaListado);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Buscar:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 22));

        btn_salir.setBackground(new java.awt.Color(51, 51, 51));
        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/if_Log Out_24x24.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setMaximumSize(new java.awt.Dimension(143, 41));
        btn_salir.setMinimumSize(new java.awt.Dimension(143, 41));
        btn_salir.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(51, 51, 51));
        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/if_Remove_24x24.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_buscar.setBackground(new java.awt.Color(51, 51, 51));
        btn_buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/if_Search_24x24.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setMaximumSize(new java.awt.Dimension(143, 41));
        btn_buscar.setMinimumSize(new java.awt.Dimension(143, 41));
        btn_buscar.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        txt_buscar.setMaximumSize(new java.awt.Dimension(6, 21));
        txt_buscar.setMinimumSize(new java.awt.Dimension(6, 21));
        txt_buscar.setPreferredSize(new java.awt.Dimension(6, 21));
        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });

        lblTotalRegistros.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalRegistros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalRegistros.setText("Registros");
        lblTotalRegistros.setPreferredSize(new java.awt.Dimension(60, 22));

        javax.swing.GroupLayout listaResponsablesLayout = new javax.swing.GroupLayout(listaResponsables);
        listaResponsables.setLayout(listaResponsablesLayout);
        listaResponsablesLayout.setHorizontalGroup(
            listaResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaResponsablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listaResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(listaResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(listaResponsablesLayout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        listaResponsablesLayout.setVerticalGroup(
            listaResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaResponsablesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(listaResponsablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );

        getContentPane().add(listaResponsables, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 730, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_docente_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_docente_nombreActionPerformed
        txt_docente_nombre.transferFocus();
    }//GEN-LAST:event_txt_docente_nombreActionPerformed

    private void txt_docente_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_docente_nombreKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar Sólo Letras", "Advertencia", 2);
            txt_docente_nombre.setCursor(null);
        }
    }//GEN-LAST:event_txt_docente_nombreKeyTyped

    private void txt_docente_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_docente_apellidoActionPerformed
        txt_docente_apellido.transferFocus();
    }//GEN-LAST:event_txt_docente_apellidoActionPerformed

    private void txt_docente_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_docente_apellidoKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar Sólo Letras", "Advertencia", 2);
            txt_docente_apellido.setCursor(null);
        }
    }//GEN-LAST:event_txt_docente_apellidoKeyTyped

    private void txt_docente_dni_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_docente_dni_dActionPerformed
        txt_docente_dni_d.transferFocus();
    }//GEN-LAST:event_txt_docente_dni_dActionPerformed

    private void txt_docente_dni_dKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_docente_dni_dKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar) || Character.isSpaceChar(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar Sólo Números", "Advertencia", 2);
            txt_docente_dni_d.setCursor(null);
        }
    }//GEN-LAST:event_txt_docente_dni_dKeyTyped

    private void txt_docente_telefono_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_docente_telefono_areaActionPerformed
        txt_docente_telefono_area.transferFocus();
    }//GEN-LAST:event_txt_docente_telefono_areaActionPerformed

    private void txt_docente_telefono_areaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_docente_telefono_areaKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar) || Character.isSpaceChar(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar Sólo Números", "Advertencia", 2);
            txt_docente_telefono_area.setCursor(null);
        }
    }//GEN-LAST:event_txt_docente_telefono_areaKeyTyped

    private void txt_docente_telefono_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_docente_telefono_numeroActionPerformed
        txt_docente_telefono_numero.transferFocus();
    }//GEN-LAST:event_txt_docente_telefono_numeroActionPerformed

    private void txt_docente_telefono_numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_docente_telefono_numeroKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar) || Character.isSpaceChar(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar Sólo Números", "Advertencia", 2);
            txt_docente_telefono_numero.setCursor(null);
        }
    }//GEN-LAST:event_txt_docente_telefono_numeroKeyTyped

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        habilitar();
        btn_guardar.setText("Guardar");
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        inhabilitar();
        btn_guardar.setText("Guardar");
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void cbo_tipo_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_tipo_telefonoActionPerformed
        cbo_tipo_telefono.transferFocus();
        if (cbo_tipo_telefono.getSelectedItem() == "Fijo") {
            telefono_15.setVisible(false);
        } else {
            telefono_15.setVisible(true);
        }
    }//GEN-LAST:event_cbo_tipo_telefonoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Realmente deseas salir?", "Confirmar Salida", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if (opcion == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        btn_buscar.transferFocus();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void tablaListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListadoMouseClicked
        btn_guardar.setText("Editar");
    }//GEN-LAST:event_tablaListadoMouseClicked

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        txt_buscar.transferFocus();
    }//GEN-LAST:event_txt_buscarActionPerformed

// metodo para crear solo una instancia del formulario al hacer click en el menu
    private static FormDocente docente;

    public static FormDocente getInstance() {
        if (docente == null) {
            docente = new FormDocente();
        }
        return docente;
    }

    public void inhabilitar() {
        txt_buscar.setEnabled(false);
        txt_docente_apellido.setEnabled(false);
        txt_docente_dni_d.setEnabled(false);
        txt_docente_nombre.setEnabled(false);
        cbo_tipo_telefono.setEnabled(false);
        txt_docente_telefono_area.setEnabled(false);
        txt_docente_telefono_numero.setEnabled(false);
        btn_agregar.setEnabled(false);
        btn_buscar.setEnabled(false);
        tablaListado.setEnabled(false);
        btn_cancelar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_guardar.setEnabled(false);
    }

    public void habilitar() {
        txt_buscar.setEnabled(true);
        txt_docente_apellido.setEnabled(true);
        txt_docente_dni_d.setEnabled(true);
        txt_docente_nombre.setEnabled(true);
        cbo_tipo_telefono.setEnabled(true);
        txt_docente_telefono_area.setEnabled(true);
        txt_docente_telefono_numero.setEnabled(true);
        btn_agregar.setEnabled(true);
        btn_buscar.setEnabled(true);
        tablaListado.setEnabled(true);
        btn_cancelar.setEnabled(true);
        btn_eliminar.setEnabled(true);
        btn_guardar.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DApellido;
    private javax.swing.JLabel DDNI;
    private javax.swing.JLabel DNombre;
    private javax.swing.JLabel DTelefono;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cbo_tipo_telefono;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalRegistros;
    private javax.swing.JPanel listaResponsables;
    private javax.swing.JPanel registroResponsables;
    private javax.swing.JTable tablaListado;
    private javax.swing.JLabel telefono_0;
    private javax.swing.JLabel telefono_15;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_docente_apellido;
    private javax.swing.JTextField txt_docente_dni_d;
    private javax.swing.JTextField txt_docente_nombre;
    private javax.swing.JTextField txt_docente_telefono_area;
    private javax.swing.JTextField txt_docente_telefono_numero;
    // End of variables declaration//GEN-END:variables
}
