/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mil.sda111mil.forms;

import com.mil.sda111mil.services.Service;
import com.mil.sda111mil.beans.Alumno;
import com.mil.sda111mil.beans.Curso;
import com.mil.sda111mil.beans.Responsable;
import com.mil.sda111mil.beans.Telefono;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CF02
 */
public class FormAlumno extends javax.swing.JInternalFrame {

    public Integer totalregistros;

    /**
     * Creates new form FormAlumno
     */
    public FormAlumno() {
        initComponents();
        cleanAlumnoForm();
        inhabilitar();
        cboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        mostrarListaAlumnos();

    }

    public void mostrarListaAlumnos() {
        List<Alumno> lista = Service.listarAlumnos();
        jTextCantAlumnos.setText(String.valueOf(lista.size()));
        mostrarAlumno(lista);
    }

    public void mostrarAlumnoBuscado() {
        List<Alumno> lista = Service.encontrarAlumno(txt_buscar_nombre.getText(), txt_buscar_apellido.getText());
        mostrarAlumno(lista);
    }

    private void mostrarAlumno(List<Alumno> lista) {
        DefaultTableModel modelo;
        String[] titulos = {"DNI", "Apellido", "Nombre", "Curso", "Fecha de Nacimiento", "Sexo"};
        modelo = new NoEditableModel(null, titulos);

        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        for (Alumno a : lista) {
            Object[] o = new Object[6];
            o[0] = a.getDni();
            o[1] = a.getApellido();
            o[2] = a.getNombre();
            o[3] = a.getCurso();
            o[4] = df.format(a.getFechaNacimiento());
            o[5] = a.getSexo();
            modelo.addRow(o);
        }
        tablaListado.setAutoCreateRowSorter(true);
        tablaListado.setModel(modelo);

        tablaListado.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {

                // do some actions here, for example
                // print first column value from selected row
                if (tablaListado.getSelectedRow() >= 0) {
                    String dni = tablaListado.getValueAt(tablaListado.getSelectedRow(), 0).toString();
                    cargarFichaAlumno(dni);
                }
            }
        });
    }
    // ya tenes el dni .. llamar metodo que devuelva el Alumno y empezar a setear los datos que faltan

    private void cargarFichaAlumno(String dni) {
        habilitarEdicion();
        String[] model = listarCursos();
        cboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(model));

        Alumno elegido = Service.listarPorDni(dni);
        txt_dni_a.setText(dni);
        txt_nombre.setText(elegido.getNombre());
        txt_apellido.setText(elegido.getApellido());
        txt_domicilio.setText(elegido.getDireccion());
        cboCurso.setSelectedIndex(elegido.getCurso().getIdcurso() - 1);
        fechaNacimiento.setDate(elegido.getFechaNacimiento());

        txt_dni_r.setText("" + elegido.getResponsable().getDni());
        txt_responsable_nombre.setText(elegido.getResponsable().getNombre());
        txt_dni_r.setEditable(false);
        txt_responsable_apellido.setText(elegido.getResponsable().getApellido());
        List<Telefono> listTelefonos = elegido.getResponsable().getTelefonos();
        txt_responsable_telefono_area.setText(String.valueOf(listTelefonos.get(0).getNumero().getCodigoArea()));
        txt_responsable_telefono_numero.setText(String.valueOf(listTelefonos.get(0).getNumero().getNroTelefono()));

        if (elegido.getSexo().equals("M")) {
            cboSexo.getModel().setSelectedItem("Masculino");
        } else {
            cboSexo.getModel().setSelectedItem("Femenino");
        }

        cargarFotoAlumno(elegido.getDni());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listadoAlumnos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListado = new javax.swing.JTable();
        txt_buscar_apellido = new javax.swing.JTextField();
        lblTotalRegistros = new javax.swing.JLabel();
        txt_buscar_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_nuevo = new javax.swing.JButton();
        jTextCantAlumnos = new javax.swing.JTextField();
        btn_refresh = new javax.swing.JButton();
        registroAlumnos = new javax.swing.JPanel();
        DNI = new javax.swing.JLabel();
        txt_dni_a = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        Domicilio = new javax.swing.JLabel();
        txt_domicilio = new javax.swing.JTextField();
        Curso = new javax.swing.JLabel();
        cboCurso = new javax.swing.JComboBox<>();
        Responsable = new javax.swing.JLabel();
        Nacimiento = new javax.swing.JLabel();
        fechaNacimiento = new com.toedter.calendar.JDateChooser();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        Sexo = new javax.swing.JLabel();
        cboSexo = new javax.swing.JComboBox<>();
        DNIr = new javax.swing.JLabel();
        txt_dni_r = new javax.swing.JTextField();
        Nombre_r = new javax.swing.JLabel();
        txt_responsable_nombre = new javax.swing.JTextField();
        Apellido_r = new javax.swing.JLabel();
        txt_responsable_apellido = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        txt_responsable_telefono_area = new javax.swing.JTextField();
        txt_responsable_telefono_numero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_modificar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alumno");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listadoAlumnos.setBackground(new java.awt.Color(255, 204, 204));
        listadoAlumnos.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Alumnos"));
        listadoAlumnos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Apellido:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 22));
        listadoAlumnos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 38, 60, 30));

        btn_salir.setBackground(new java.awt.Color(51, 51, 51));
        btn_salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/if_Log Out_24x24.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setMaximumSize(new java.awt.Dimension(143, 41));
        btn_salir.setMinimumSize(new java.awt.Dimension(143, 41));
        btn_salir.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        listadoAlumnos.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        btn_eliminar.setBackground(new java.awt.Color(51, 51, 51));
        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/if_Remove_24x24.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        listadoAlumnos.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        btn_buscar.setBackground(new java.awt.Color(51, 51, 51));
        btn_buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/if_Search_24x24.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setMaximumSize(new java.awt.Dimension(143, 41));
        btn_buscar.setMinimumSize(new java.awt.Dimension(143, 41));
        btn_buscar.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        listadoAlumnos.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        tablaListado.setAutoCreateRowSorter(true);
        tablaListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido", "Domicilio", "Sexo", "Fecha de Nacimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaListado.setEditingColumn(0);
        tablaListado.setEditingRow(0);
        tablaListado.getTableHeader().setReorderingAllowed(false);
        tablaListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaListado);
        if (tablaListado.getColumnModel().getColumnCount() > 0) {
            tablaListado.getColumnModel().getColumn(0).setMinWidth(85);
            tablaListado.getColumnModel().getColumn(0).setPreferredWidth(85);
            tablaListado.getColumnModel().getColumn(0).setMaxWidth(85);
            tablaListado.getColumnModel().getColumn(4).setMinWidth(85);
            tablaListado.getColumnModel().getColumn(4).setPreferredWidth(85);
            tablaListado.getColumnModel().getColumn(4).setMaxWidth(85);
        }

        listadoAlumnos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 690, 460));

        txt_buscar_apellido.setMaximumSize(new java.awt.Dimension(6, 21));
        txt_buscar_apellido.setMinimumSize(new java.awt.Dimension(6, 21));
        txt_buscar_apellido.setPreferredSize(new java.awt.Dimension(6, 21));
        listadoAlumnos.add(txt_buscar_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 38, 110, 30));

        lblTotalRegistros.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalRegistros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalRegistros.setText("Registros");
        lblTotalRegistros.setPreferredSize(new java.awt.Dimension(60, 22));
        listadoAlumnos.add(lblTotalRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 70, 30));

        txt_buscar_nombre.setMaximumSize(new java.awt.Dimension(6, 21));
        txt_buscar_nombre.setMinimumSize(new java.awt.Dimension(6, 21));
        txt_buscar_nombre.setPreferredSize(new java.awt.Dimension(6, 21));
        txt_buscar_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscar_nombreActionPerformed(evt);
            }
        });
        listadoAlumnos.add(txt_buscar_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 38, 110, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 22));
        listadoAlumnos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 38, 70, 30));

        btn_nuevo.setBackground(new java.awt.Color(51, 51, 51));
        btn_nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/if_Add_24x24.png"))); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.setBorder(null);
        btn_nuevo.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        listadoAlumnos.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jTextCantAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCantAlumnosActionPerformed(evt);
            }
        });
        listadoAlumnos.add(jTextCantAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 40, 30));

        btn_refresh.setBackground(new java.awt.Color(51, 51, 51));
        btn_refresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_refresh.setForeground(new java.awt.Color(255, 255, 255));
        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/reload-icon_24x24.png"))); // NOI18N
        btn_refresh.setText("Actualizar");
        btn_refresh.setMaximumSize(new java.awt.Dimension(143, 41));
        btn_refresh.setMinimumSize(new java.awt.Dimension(143, 41));
        btn_refresh.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        listadoAlumnos.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));

        getContentPane().add(listadoAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 730, 680));

        registroAlumnos.setBackground(new java.awt.Color(204, 204, 255));
        registroAlumnos.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Alumnos"));
        registroAlumnos.setForeground(new java.awt.Color(250, 250, 250));
        registroAlumnos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DNI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DNI.setText("DNI:");
        DNI.setMaximumSize(new java.awt.Dimension(60, 15));
        DNI.setMinimumSize(new java.awt.Dimension(60, 15));
        DNI.setPreferredSize(new java.awt.Dimension(60, 22));
        registroAlumnos.add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, 30));

        txt_dni_a.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_dni_a.setPreferredSize(new java.awt.Dimension(100, 25));
        txt_dni_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dni_aActionPerformed(evt);
            }
        });
        txt_dni_a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dni_aKeyTyped(evt);
            }
        });
        registroAlumnos.add(txt_dni_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 190, 30));

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nombre.setText("Nombre:");
        Nombre.setMaximumSize(new java.awt.Dimension(60, 15));
        Nombre.setMinimumSize(new java.awt.Dimension(60, 15));
        Nombre.setPreferredSize(new java.awt.Dimension(60, 22));
        registroAlumnos.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 70, 30));

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nombre.setPreferredSize(new java.awt.Dimension(100, 25));
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        registroAlumnos.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 78, 190, 30));

        Apellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Apellido.setText("Apellido:");
        Apellido.setMaximumSize(new java.awt.Dimension(60, 15));
        Apellido.setMinimumSize(new java.awt.Dimension(60, 15));
        Apellido.setPreferredSize(new java.awt.Dimension(60, 22));
        registroAlumnos.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, 70, 30));

        txt_apellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_apellido.setPreferredSize(new java.awt.Dimension(100, 25));
        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });
        txt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoKeyTyped(evt);
            }
        });
        registroAlumnos.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 118, 190, 30));

        Domicilio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Domicilio.setText("Domicilio:");
        Domicilio.setMaximumSize(new java.awt.Dimension(60, 15));
        Domicilio.setMinimumSize(new java.awt.Dimension(60, 15));
        Domicilio.setPreferredSize(new java.awt.Dimension(60, 22));
        registroAlumnos.add(Domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, 80, 30));

        txt_domicilio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_domicilio.setPreferredSize(new java.awt.Dimension(100, 25));
        txt_domicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_domicilioActionPerformed(evt);
            }
        });
        txt_domicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_domicilioKeyTyped(evt);
            }
        });
        registroAlumnos.add(txt_domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 158, 190, 30));

        Curso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Curso.setText("Curso:");
        Curso.setMaximumSize(new java.awt.Dimension(60, 15));
        Curso.setMinimumSize(new java.awt.Dimension(60, 15));
        Curso.setPreferredSize(new java.awt.Dimension(60, 22));
        registroAlumnos.add(Curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 238, -1, 30));

        cboCurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cboCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCursoActionPerformed(evt);
            }
        });
        registroAlumnos.add(cboCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 238, 190, 30));

        Responsable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Responsable.setText("Responsable:");
        Responsable.setMaximumSize(new java.awt.Dimension(60, 15));
        Responsable.setMinimumSize(new java.awt.Dimension(60, 15));
        Responsable.setPreferredSize(new java.awt.Dimension(60, 22));
        registroAlumnos.add(Responsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 288, 100, 30));

        Nacimiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nacimiento.setText("Fecha de Nacimiento:");
        Nacimiento.setMaximumSize(new java.awt.Dimension(60, 15));
        Nacimiento.setMinimumSize(new java.awt.Dimension(60, 15));
        Nacimiento.setPreferredSize(new java.awt.Dimension(60, 22));
        registroAlumnos.add(Nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 198, 160, 30));

        fechaNacimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechaNacimiento.setPreferredSize(new java.awt.Dimension(170, 30));
        registroAlumnos.add(fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 198, 190, 30));

        btn_guardar.setBackground(new java.awt.Color(51, 51, 51));
        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/if_Save_24x24.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        registroAlumnos.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, -1, -1));

        btn_cancelar.setBackground(new java.awt.Color(51, 51, 51));
        btn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/if_Cancel_24x24.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        registroAlumnos.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, -1, -1));

        Sexo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sexo.setText("Sexo:");
        Sexo.setMaximumSize(new java.awt.Dimension(60, 15));
        Sexo.setMinimumSize(new java.awt.Dimension(60, 15));
        Sexo.setPreferredSize(new java.awt.Dimension(60, 22));
        registroAlumnos.add(Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 198, 50, 30));

        cboSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        registroAlumnos.add(cboSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 198, 100, 30));

        DNIr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DNIr.setText("DNI:");
        DNIr.setMaximumSize(new java.awt.Dimension(60, 15));
        DNIr.setMinimumSize(new java.awt.Dimension(60, 15));
        DNIr.setPreferredSize(new java.awt.Dimension(60, 22));
        registroAlumnos.add(DNIr, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 70, 30));

        txt_dni_r.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_dni_r.setPreferredSize(new java.awt.Dimension(100, 25));
        txt_dni_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dni_rActionPerformed(evt);
            }
        });
        txt_dni_r.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dni_rKeyTyped(evt);
            }
        });
        registroAlumnos.add(txt_dni_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 170, 30));

        Nombre_r.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nombre_r.setText("Nombre:");
        Nombre_r.setMaximumSize(new java.awt.Dimension(60, 15));
        Nombre_r.setMinimumSize(new java.awt.Dimension(60, 15));
        Nombre_r.setPreferredSize(new java.awt.Dimension(60, 22));
        registroAlumnos.add(Nombre_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 70, 30));

        txt_responsable_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_responsable_nombre.setPreferredSize(new java.awt.Dimension(100, 25));
        txt_responsable_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_responsable_nombreActionPerformed(evt);
            }
        });
        txt_responsable_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_responsable_nombreKeyTyped(evt);
            }
        });
        registroAlumnos.add(txt_responsable_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 170, 30));

        Apellido_r.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Apellido_r.setText("Apellido:");
        Apellido_r.setMaximumSize(new java.awt.Dimension(60, 15));
        Apellido_r.setMinimumSize(new java.awt.Dimension(60, 15));
        Apellido_r.setPreferredSize(new java.awt.Dimension(60, 22));
        registroAlumnos.add(Apellido_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 80, 30));

        txt_responsable_apellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_responsable_apellido.setPreferredSize(new java.awt.Dimension(100, 25));
        txt_responsable_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_responsable_apellidoActionPerformed(evt);
            }
        });
        txt_responsable_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_responsable_apellidoKeyTyped(evt);
            }
        });
        registroAlumnos.add(txt_responsable_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 170, 30));

        Telefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Telefono.setText("Teléfono:");
        Telefono.setMaximumSize(new java.awt.Dimension(60, 15));
        Telefono.setMinimumSize(new java.awt.Dimension(60, 15));
        Telefono.setPreferredSize(new java.awt.Dimension(60, 22));
        registroAlumnos.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 80, 30));

        txt_responsable_telefono_area.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_responsable_telefono_area.setMaximumSize(new java.awt.Dimension(100, 25));
        txt_responsable_telefono_area.setMinimumSize(new java.awt.Dimension(100, 25));
        txt_responsable_telefono_area.setPreferredSize(new java.awt.Dimension(100, 25));
        txt_responsable_telefono_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_responsable_telefono_areaActionPerformed(evt);
            }
        });
        txt_responsable_telefono_area.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_responsable_telefono_areaKeyTyped(evt);
            }
        });
        registroAlumnos.add(txt_responsable_telefono_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 65, 30));

        txt_responsable_telefono_numero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_responsable_telefono_numero.setPreferredSize(new java.awt.Dimension(100, 25));
        txt_responsable_telefono_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_responsable_telefono_numeroActionPerformed(evt);
            }
        });
        txt_responsable_telefono_numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_responsable_telefono_numeroKeyTyped(evt);
            }
        });
        registroAlumnos.add(txt_responsable_telefono_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 100, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 160));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 160));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 160));
        registroAlumnos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 150, 160));

        btn_modificar.setBackground(new java.awt.Color(51, 51, 51));
        btn_modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/24x24/Edit_24x24.png"))); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        registroAlumnos.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, -1, -1));

        getContentPane().add(registroAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_dni_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dni_aActionPerformed
        txt_dni_a.transferFocus();
    }//GEN-LAST:event_txt_dni_aActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        txt_nombre.transferFocus();
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
        txt_apellido.transferFocus();
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void txt_domicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_domicilioActionPerformed
        txt_domicilio.transferFocus();
    }//GEN-LAST:event_txt_domicilioActionPerformed

    private void cboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCursoActionPerformed
        cboCurso.transferFocus();
    }//GEN-LAST:event_cboCursoActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        habilitar();
        cleanAlumnoForm();
        cargarFotoAlumno(0);
        btn_cancelar.setEnabled(true);
        btn_guardar.setText("Guardar");
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        if (txt_dni_a.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un DNI para el Alumno");
            txt_dni_a.requestFocus();
            return;
        }
        if (txt_nombre.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Nombre para el Alumno");
            txt_nombre.requestFocus();
            return;
        }
        if (txt_apellido.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Apellido para el Alumno");
            txt_apellido.requestFocus();
            return;
        }
        if (txt_domicilio.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Domicilio para el Alumno");
            txt_domicilio.requestFocus();
            return;
        }
        if (fechaNacimiento.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Fecha de Nacimiento para el Alumno");
            fechaNacimiento.requestFocus();
            return;
        }
        // Vacio todos los campos de texto limpio la lista de seleccion de curso y limpio el campo de la fecha
        Responsable respon = Service.crearResponsable(txt_responsable_apellido.getText(), txt_responsable_nombre.getText(),
                Integer.valueOf(txt_dni_r.getText()), Integer.valueOf(txt_responsable_telefono_area.getText()), Integer.valueOf(txt_responsable_telefono_numero.getText()));
        int sexoAlumno = cboSexo.getSelectedIndex();
        String genero = "M";
        if (sexoAlumno == 1) {
            genero = "F";
        }
        Service.crearAlumno(txt_apellido.getText(), txt_nombre.getText(), Integer.valueOf(txt_dni_a.getText()), txt_domicilio.getText(),
                cboCurso.getSelectedIndex() + 1, fechaNacimiento.getDate(), genero, respon);

        inhabilitar();
        cleanAlumnoForm();
        btn_guardar.setEnabled(false);
        btn_cancelar.setEnabled(true);
        JOptionPane.showMessageDialog(rootPane, "Los Datos Fueron Guardados Exitosamente");
        mostrarListaAlumnos();
        btn_guardar.setText("Guardar");
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        cleanAlumnoForm();

    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        mostrarAlumnoBuscado();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Realmente deseas salir?", "Confirmar Salida", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        if (opcion == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btn_salirActionPerformed

    private void tablaListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListadoMouseClicked
        //  btn_guardar.setText("Editar");
    }//GEN-LAST:event_tablaListadoMouseClicked

    private void txt_dni_aKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dni_aKeyTyped
        char validar = evt.getKeyChar();
        if ((validar < '0' || validar > '9') && (validar != (char) KeyEvent.VK_BACK_SPACE) && (validar != (char) KeyEvent.VK_ENTER) && (validar < '°' || validar > '°')) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar Sólo Números", "Advertencia", 2);
            txt_dni_a.setCursor(null);
        }
    }//GEN-LAST:event_txt_dni_aKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar Sólo Letras", "Advertencia", 2);
            txt_nombre.setCursor(null);
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar Sólo Letras", "Advertencia", 2);
            txt_apellido.setCursor(null);
        }
    }//GEN-LAST:event_txt_apellidoKeyTyped

    private void txt_domicilioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_domicilioKeyTyped
        char validar = evt.getKeyChar();
        if ((validar < '0' || validar > '9') && (validar < '.' || validar > '.') && (validar < 'a' || validar > 'z') && (validar < 'A' || validar > 'Z') && (validar > 'ñ' || validar < 'Ñ') && (validar != (char) KeyEvent.VK_BACK_SPACE) && (validar != (char) KeyEvent.VK_SPACE) && (validar != (char) KeyEvent.VK_ENTER) && (validar < 'º' || validar > 'º')) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar Sólo Caracteres Válidos", "Advertencia", 2);
            txt_domicilio.setCursor(null);
        }


    }//GEN-LAST:event_txt_domicilioKeyTyped

    private void txt_buscar_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscar_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar_nombreActionPerformed

    private void txt_dni_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dni_rActionPerformed
        txt_nombre.transferFocus();
    }//GEN-LAST:event_txt_dni_rActionPerformed

    private void txt_dni_rKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dni_rKeyTyped
        char validar = evt.getKeyChar();
        if ((validar < '0' || validar > '9') && (validar != (char) KeyEvent.VK_BACK_SPACE) && (validar != (char) KeyEvent.VK_ENTER) && (validar < '°' || validar > '°')) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar Sólo Números", "Advertencia", 2);
            txt_dni_a.setCursor(null);
        }
    }//GEN-LAST:event_txt_dni_rKeyTyped

    private void txt_responsable_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_responsable_nombreActionPerformed
        txt_apellido.transferFocus();
    }//GEN-LAST:event_txt_responsable_nombreActionPerformed

    private void txt_responsable_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_responsable_nombreKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar Sólo Letras", "Advertencia", 2);
            txt_apellido.setCursor(null);
        }
    }//GEN-LAST:event_txt_responsable_nombreKeyTyped

    private void txt_responsable_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_responsable_apellidoActionPerformed
        txt_domicilio.transferFocus();
    }//GEN-LAST:event_txt_responsable_apellidoActionPerformed

    private void txt_responsable_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_responsable_apellidoKeyTyped
        char validar = evt.getKeyChar();
        if ((validar < '0' || validar > '9') && (validar < '.' || validar > '.') && (validar < 'a' || validar > 'z') && (validar < 'A' || validar > 'Z') && (validar > 'ñ' || validar < 'Ñ') && (validar != (char) KeyEvent.VK_BACK_SPACE) && (validar != (char) KeyEvent.VK_SPACE) && (validar != (char) KeyEvent.VK_ENTER) && (validar < 'º' || validar > 'º')) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar Sólo Caracteres Válidos", "Advertencia", 2);
            txt_domicilio.setCursor(null);
        }
    }//GEN-LAST:event_txt_responsable_apellidoKeyTyped

    private void txt_responsable_telefono_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_responsable_telefono_areaActionPerformed
        txt_responsable_telefono_area.transferFocus();
    }//GEN-LAST:event_txt_responsable_telefono_areaActionPerformed

    private void txt_responsable_telefono_areaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_responsable_telefono_areaKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar) || Character.isSpaceChar(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar Sólo Números", "Advertencia", 2);
            txt_responsable_telefono_area.setCursor(null);
        }
    }//GEN-LAST:event_txt_responsable_telefono_areaKeyTyped

    private void txt_responsable_telefono_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_responsable_telefono_numeroActionPerformed
        txt_responsable_telefono_numero.transferFocus();
    }//GEN-LAST:event_txt_responsable_telefono_numeroActionPerformed

    private void txt_responsable_telefono_numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_responsable_telefono_numeroKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar) || Character.isSpaceChar(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Debes Ingresar Sólo Números", "Advertencia", 2);
            txt_responsable_telefono_numero.setCursor(null);
        }
    }//GEN-LAST:event_txt_responsable_telefono_numeroKeyTyped

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if (tablaListado.getSelectedRow() >= 0) {
            String dni = tablaListado.getValueAt(tablaListado.getSelectedRow(), 0).toString();
            Service.bajaAlumno(Integer.valueOf(dni));
            cleanAlumnoForm();
            cboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
            mostrarListaAlumnos();
            JOptionPane.showMessageDialog(rootPane, "El Alumno con DNI = " + dni + " fue eliminado Exitosamente");

        }


    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed

        if (txt_dni_a.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un DNI para el Alumno");
            txt_dni_a.requestFocus();
            return;
        }
        if (txt_nombre.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Nombre para el Alumno");
            txt_nombre.requestFocus();
            return;
        }
        if (txt_apellido.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Apellido para el Alumno");
            txt_apellido.requestFocus();
            return;
        }
        if (txt_domicilio.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Domicilio para el Alumno");
            txt_domicilio.requestFocus();
            return;
        }
        if (fechaNacimiento.getDate() == null) {
            JOptionPane.showMessageDialog(rootPane, "Debes ingresar un Fecha de Nacimiento para el Alumno");
            fechaNacimiento.requestFocus();
            return;
        }

        if (tablaListado.getSelectedRow() >= 0) {
            String dni = tablaListado.getValueAt(tablaListado.getSelectedRow(), 0).toString();
            int sexoAlumno = cboSexo.getSelectedIndex();
            String genero = "M";
            if (sexoAlumno == 1) {
                genero = "F";
            }
            Service.modificarAlumno(Integer.valueOf(dni), txt_apellido.getText(), txt_nombre.getText(), txt_domicilio.getText(),
                    fechaNacimiento.getDate(), cboCurso.getSelectedIndex() + 1, genero);
            cleanAlumnoForm();
            cboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
            mostrarListaAlumnos();
            inhabilitar();
            JOptionPane.showMessageDialog(rootPane, "El Alumno con DNI = " + dni + " fue Modificado Exitosamente");
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void jTextCantAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCantAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCantAlumnosActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        mostrarListaAlumnos();
        cleanAlumnoForm();
        cboCurso.setSelectedIndex(0);
        
    }//GEN-LAST:event_btn_refreshActionPerformed
    // metodo para crear solo una instancia del formulario al hacer click en el menu
    private static FormAlumno alumno;

    public static FormAlumno getInstance() {
        if (alumno == null) {
            alumno = new FormAlumno();
        }
        return alumno;
    }

    private void cleanAlumnoForm() {
        txt_dni_a.setText("");
        txt_apellido.setText("");
        txt_buscar_apellido.setText("");
        txt_domicilio.setText("");
        txt_nombre.setText("");
        txt_responsable_apellido.setText("");
        txt_responsable_nombre.setText("");
        txt_dni_r.setText("");
        txt_dni_r.setEditable(true);
        txt_responsable_telefono_area.setText("");
        txt_responsable_telefono_numero.setText("");
        fechaNacimiento.setCalendar(null);
        btn_buscar.setEnabled(true);
        btn_cancelar.setEnabled(false);
        btn_eliminar.setEnabled(true);
    }

    public void inhabilitar() {
        txt_apellido.setEnabled(false);
        txt_dni_a.setEnabled(false);
        txt_domicilio.setEnabled(false);
        txt_nombre.setEnabled(false);
        cboCurso.setEnabled(false);
        fechaNacimiento.setEnabled(false);
        cboSexo.setEnabled(false);

        txt_responsable_apellido.setEnabled(false);
        txt_responsable_nombre.setEnabled(false);
        txt_dni_r.setEditable(false);
        txt_dni_r.setEnabled(false);
        txt_responsable_telefono_area.setEnabled(false);
        txt_responsable_telefono_numero.setEnabled(false);

        btn_cancelar.setEnabled(false);
        btn_guardar.setEnabled(false);
        btn_modificar.setEnabled(false);

    }

    public void habilitarEdicion() {
        txt_apellido.setEnabled(true);
        txt_dni_a.setEnabled(false);
        txt_domicilio.setEnabled(true);
        txt_nombre.setEnabled(true);
        cboCurso.setEnabled(true);
        fechaNacimiento.setEnabled(true);
        cboSexo.setEnabled(true);

        txt_responsable_apellido.setEnabled(false);
        txt_responsable_nombre.setEnabled(false);
        txt_dni_r.setEditable(false);
        txt_dni_r.setEnabled(false);
        txt_responsable_telefono_area.setEnabled(false);
        txt_responsable_telefono_numero.setEnabled(false);

        btn_cancelar.setEnabled(false);
        btn_guardar.setEnabled(false);
        btn_modificar.setEnabled(true);

    }

    public void habilitar() {
        String[] model = listarCursos();
        cboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(model));
        cboCurso.setSelectedItem(model[0]);
        txt_apellido.setEnabled(true);
        txt_buscar_apellido.setEnabled(true);
        txt_dni_a.setEnabled(true);
        tablaListado.setEnabled(true);
        txt_domicilio.setEnabled(true);
        txt_nombre.setEnabled(true);
        cboCurso.setEnabled(true);
        txt_responsable_apellido.setEnabled(true);
        txt_responsable_nombre.setEnabled(true);
        txt_dni_r.setEditable(true);
        txt_dni_r.setEnabled(true);
        txt_responsable_telefono_area.setEnabled(true);
        txt_responsable_telefono_numero.setEnabled(true);

        fechaNacimiento.setEnabled(true);
        cboSexo.setEnabled(true);
        btn_buscar.setEnabled(true);
        btn_cancelar.setEnabled(true);
        btn_eliminar.setEnabled(true);
        btn_guardar.setEnabled(true);
        btn_modificar.setEnabled(false);
        //listaCursos.setEnabled(true);
    }

    private String[] listarCursos() {

        List<Curso> l = Service.listarCursos();
        String[] model = new String[l.size()];
        int i = 0;
        for (Curso curso : l) {
            model[i] = curso.getCurso() + "º " + curso.getDivision();
            i++;
        }
        return model;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel Apellido_r;
    private javax.swing.JLabel Curso;
    private javax.swing.JLabel DNI;
    private javax.swing.JLabel DNIr;
    private javax.swing.JLabel Domicilio;
    private javax.swing.JLabel Nacimiento;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre_r;
    private javax.swing.JLabel Responsable;
    private javax.swing.JLabel Sexo;
    private javax.swing.JLabel Telefono;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cboCurso;
    private javax.swing.JComboBox<String> cboSexo;
    private com.toedter.calendar.JDateChooser fechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCantAlumnos;
    private javax.swing.JLabel lblTotalRegistros;
    private javax.swing.JPanel listadoAlumnos;
    private javax.swing.JPanel registroAlumnos;
    private javax.swing.JTable tablaListado;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_buscar_apellido;
    private javax.swing.JTextField txt_buscar_nombre;
    private javax.swing.JTextField txt_dni_a;
    private javax.swing.JTextField txt_dni_r;
    private javax.swing.JTextField txt_domicilio;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_responsable_apellido;
    private javax.swing.JTextField txt_responsable_nombre;
    private javax.swing.JTextField txt_responsable_telefono_area;
    private javax.swing.JTextField txt_responsable_telefono_numero;
    // End of variables declaration//GEN-END:variables

    private void cargarFotoAlumno(int dni) {
        ImageIcon imageIcon;
        try {
            imageIcon = new ImageIcon(getClass().getResource("/fotos/" + dni + ".jpg"));
        } catch (Exception e) {
            imageIcon = new ImageIcon(getClass().getResource("/fotos/no_foto.jpg"));
        }
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(160, 160, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);
        jLabel1.setIcon(imageIcon);
    }

    
    
}
