-- MySQL Script generated by MySQL Workbench
-- Tue May 22 19:51:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sql10240625
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sql10240625
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sql10240625` DEFAULT CHARACTER SET latin1 ;
USE `sql10240625` ;

-- -----------------------------------------------------
-- Table `sql10240625`.`preceptor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10240625`.`preceptor` (
  `dni_p` INT NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  PRIMARY KEY (`dni_p`),
  UNIQUE INDEX `dni_p_UNIQUE` (`dni_p` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10240625`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10240625`.`curso` (
  `idcurso` INT NOT NULL,
  `curso` INT NOT NULL,
  `division` VARCHAR(45) NOT NULL,
  `turno` VARCHAR(45) NOT NULL,
  `preceptor_dni_p` INT NOT NULL,
  PRIMARY KEY (`idcurso`, `preceptor_dni_p`),
  INDEX `fk_curso_preceptor1_idx` (`preceptor_dni_p` ASC),
  CONSTRAINT `fk_curso_preceptor1`
    FOREIGN KEY (`preceptor_dni_p`)
    REFERENCES `sql10240625`.`preceptor` (`dni_p`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)asistencia
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10240625`.`responsable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10240625`.`responsable` (
  `dni_r` INT NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dni_r`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `sql10240625`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10240625`.`alumno` (
  `dni_a` INT NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  `curso_idcurso` INT NOT NULL,
  `responsable_dni_r` INT NOT NULL,
  PRIMARY KEY (`dni_a`, `curso_idcurso`, `responsable_dni_r`),
  UNIQUE INDEX `idalumno_UNIQUE` (`dni_a` ASC),
  INDEX `fk_alumno_curso1_idx` (`curso_idcurso` ASC),
  INDEX `fk_alumno_responsable1_idx` (`responsable_dni_r` ASC),
  CONSTRAINT `fk_alumno_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `sql10240625`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_responsable1`
    FOREIGN KEY (`responsable_dni_r`)
    REFERENCES `sql10240625`.`responsable` (`dni_r`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `sql10240625`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10240625`.`asistencia` (
  `fecha` DATE NOT NULL,
  `turno` TINYINT(2) NOT NULL,
  `asistencia` TINYINT NOT NULL,
  `alumno_dni_a` INT NOT NULL,
  PRIMARY KEY (`fecha`, `turno`, `alumno_dni_a`),
  UNIQUE INDEX `Fecha_UNIQUE` (`fecha` ASC),
  UNIQUE INDEX `Turno_UNIQUE` (`turno` ASC),
  INDEX `fk_asistencia_alumno_idx` (`alumno_dni_a` ASC),
  CONSTRAINT `fk_asistencia_alumno`
    FOREIGN KEY (`alumno_dni_a`)
    REFERENCES `sql10240625`.`alumno` (`dni_a`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10240625`.`calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10240625`.`calendario` (
  `fechaDesde` DATETIME NOT NULL,
  `fechaHasta` DATETIME NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fechaDesde`, `fechaHasta`),
  UNIQUE INDEX `fechaHasta_UNIQUE` (`fechaHasta` ASC),
  UNIQUE INDEX `fechaDesde_UNIQUE` (`fechaDesde` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10240625`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10240625`.`horario` (
  `dia_de_semana` VARCHAR(45) NOT NULL,
  `doble_jornada` TINYINT(1) NOT NULL,
  `curso_idcurso` INT NOT NULL,
  `curso_preceptor_dni_p` INT NOT NULL,
  PRIMARY KEY (`curso_idcurso`, `curso_preceptor_dni_p`),
  CONSTRAINT `fk_horario_curso1`
    FOREIGN KEY (`curso_idcurso` , `curso_preceptor_dni_p`)
    REFERENCES `sql10240625`.`curso` (`idcurso` , `preceptor_dni_p`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql10240625`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql10240625`.`telefono` (
  `cod_area` INT(4) NOT NULL,
  `nro_telefono` INT(7) NOT NULL,
  `tipo` TINYINT(1) NOT NULL,
  `responsable_dni_r` INT NOT NULL,
  PRIMARY KEY (`cod_area`, `nro_telefono`, `responsable_dni_r`),
  UNIQUE INDEX `cod_area_UNIQUE` (`cod_area` ASC),
  UNIQUE INDEX `nro_telefono_UNIQUE` (`nro_telefono` ASC),
  INDEX `fk_telefono_responsable1_idx` (`responsable_dni_r` ASC),
  CONSTRAINT `fk_telefono_responsable1`
    FOREIGN KEY (`responsable_dni_r`)
    REFERENCES `sql10240625`.`responsable` (`dni_r`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;